application: uberchallengesf
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /css
  static_dir: css
- url: /(.*\.(gif|png|jpg|css|js|json))
  static_files: \1
  upload: (.*\.(gif|png|jpg|css|js|json))
- url: .*
  script: main.app
